version: '3.3'

services:

  wordpress:
    image: wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_PASSWORD: docker
    volumes:
      - ./theme:/var/www/html/wp-content/themes/docker-wordpress

  mysql:
    image: mysql:5.7
    volumes:
       - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: docker

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=docker
    restart: always
    ports:
      - 3030:80
    volumes:
      - /sessions
volumes:
  db_data:
